use super::aastructs::*;
use super::font8::aa_font8;
use super::font9::aa_font9;
use super::font14::aa_font14;
use super::font16::aa_font16;
use super::fontcour::aa_fontcourier;
use super::fontgl::aa_fontgl;
use super::fontline::aa_fontline;
use super::fontx13::aa_fontX13;
use super::fontx13b::aa_fontX13B;
use super::fontx16::aa_fontX16;

pub static mut aa_fonts: [*const aa_font; 247] = unsafe {
    [
        &aa_font8 as *const aa_font,
        &aa_font9 as *const aa_font,
        &aa_font14 as *const aa_font,
        &aa_font16 as *const aa_font,
        &aa_fontX13 as *const aa_font,
        &aa_fontX13B as *const aa_font,
        &aa_fontX16 as *const aa_font,
        &aa_fontline as *const aa_font,
        &aa_fontgl as *const aa_font,
        &aa_fontcourier as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
        0 as *const aa_font,
    ]
};

pub unsafe extern "C" fn aa_registerfont(mut f: *const aa_font) -> std::ffi::c_int {
    let mut i: std::ffi::c_int = 0;
    i = 0 as std::ffi::c_int;
    while i < 246 as std::ffi::c_int && !(aa_fonts[i as usize]).is_null() {
        i += 1;
        i;
    }
    if i == 246 as std::ffi::c_int {
        return 0 as std::ffi::c_int;
    }
    aa_fonts[i as usize] = f;
    aa_fonts[(i + 1 as std::ffi::c_int) as usize] = 0 as *const aa_font;
    return 1 as std::ffi::c_int;
}
